### ISSUE TITLE
CPU/Memory Usage seems to have gone up considerably compared to earlier versions

### ISSUE THREAD

**Issue by DianaNites** [ClementTsang/bottom#343] opened 2020-12-09 15:49 UTC
### Describe the bug

Previous versions, 0.4.x I think, versions seemed to use a lot less CPU than 0.5.3 does. Especially as time goes on, I find `btm` at the top of the processes list, when it never was before.

A bit ago it was using a whole *5%*, and now seems to have settled on about 3%, which is still far more than any other single process on the system right now. The various chrome processes, Xorg, kwin, etc use about 0.1% each, for reference.

I also just noticed it's using 185 MiB of memory, which is a lot more than it should be.

These CPU/memory usage issues seems to get worse as time goes on. The way I use `bottom`, I leave it open on my terminal.

When freshly, started it uses a more reasonable 0.2% CPU and 13 MiB of memory.

### To reproduce

1. Run `btm`
2. Monitor its CPU/Memory usage
3. Wait

### bottom version (use `btm -V`)

bottom 0.5.3

### Installation method

Cargo install

### Platform

**Operating system and OS version:** Arch Linux, rolling.

**Terminal (i.e. urxvt, kitty, etc.):** Yakuake/Konsole

**Shell (i.e. zsh, bash, etc.):** Fish

_If relevant, please provide information on:_

**System info (RAM, SWAP, etc.):** 16 GB RAM, AMD Ryzen 5 2600 CPU

**Rust version (if building yourself):** rustc 1.48.0

## Additional context

Yakuake is a tabbed drop-down KDE Konsole terminal, so I leave bottom open on it so I can quickly view system information at the push of a hotkey.

Don't know exact numbers for it to build up. Current system uptime is 2 days, with bottom likely open the whole time. I've gone longer but havent seen it go to absolutely insane levels, maybe it plateaus, or maybe its just really slow and I notice its high usage and restart it often enough that it doesnt eat everything?

**Comment by ClementTsang** [comment] 2020-12-10 00:38
Hmm... thanks for the report, I'll look into it a bit.

I *am* storing more data as I get more features, so a bit more memory use doesn't sound too strange, but I know for sure I can optimize some stuff out.

**Comment by ClementTsang** [comment] 2020-12-10 00:44
Just some self-rambling:

From the behaviour you're mentioning, it sounds to me like it has to be due to processing a growing number of values as time goes on and it gathers more data.  This would also explain the growing CPU usage as it's iterating on more and more items when it tries to process it.

I should already have some code in place that automatically removes stale elements but it seems like I'm missing something...

**Comment by ClementTsang** [comment] 2020-12-10 03:39
\*groan\*

Welp, I think I figured out a significant cause of memory usage... it's because I added `trace!` logs everywhere to help debugging bug reports, but didn't realize just how much they impacted memory and CPU usage...

Starting usage without any major changes (seems to plateau out at about ~30MiB after like 20 minutes):
![image](https://user-images.githubusercontent.com/34804052/101717397-32058180-3a6d-11eb-994b-e9e7be08735f.png)

Starting usage after removing `trace!` (seems to plateau out at about ~9MiB after like 20 minutes):
![image](https://user-images.githubusercontent.com/34804052/101717695-cf60b580-3a6d-11eb-9341-b2eb75cbac83.png)

...this was totally not what I was expecting.

I'll be pushing out a release with this fix shortly.

**Comment by DianaNites** [comment] 2020-12-10 04:23
Hmm, seems weird that its only a problem as time goes on. Why does `trace!` get more expensive, or called more often? Even if logging is disabled and it just discards?

**Comment by ClementTsang** [comment] 2020-12-10 04:43
There's probably more to the issue and I'll keep digging (I'm pretty sure my earlier guess of something not being properly collected and cleaned is another issue), just found it quite surprising that the `trace!` issue seems to have been a cause of a performance regression between 0.4.7 and 0.5.x.

**Comment by ClementTsang** [comment] 2020-12-10 21:03
Yup, let the program run for like 8+ hours, there's still something causing it to grow continuously.  This should be fun to fix...

**Comment by ClementTsang** [comment] 2020-12-10 22:31
More self rambling - the issue appears (?) to be mostly in regards to the CPU data processing step in `convert_cpu_data_points`?  Will investigate this a bit further.

**Comment by ClementTsang** [comment] 2020-12-10 23:16
Think I found the problem - I had rewritten how I do the cleaning thread, but it seems that during the rewrite, I got burned by not properly doing the if logic, resulting in the cleaning event never firing.

I'll test running this again for a few hours and see if I get any issues.

**Comment by ClementTsang** [comment] 2020-12-11 03:37
Seems like that was the main issue?  I ran it for about 2-3 hours and it settled at about 10 MiB.

I'll deploy a new version of the application in a bit with this fix.

**Comment by ClementTsang** [comment] 2020-12-11 04:37
@DianaNites Deployed 0.5.4, could you try it and tell me if you get the same issues?

**Comment by DianaNites** [comment] 2020-12-11 06:06
yeah i'll update and see if I notice anymore abnormalities! Thanks so much!

**Comment by DianaNites** [comment] 2020-12-11 16:22
Been 10 hours and doesnt seem to have increased! Seems fixed!

**Comment by ClementTsang** [comment] 2020-12-11 16:37
Good to hear.  Thanks for reporting this, otherwise I probably wouldn't have caught this regression!

Going to close the issue for now, feel free to reopen if there are further issues.

**Closed by ClementTsang** 2020-12-11 16:37 UTC
Labels: bug
