### ISSUE TITLE
[Bug]: temperature sensors on some arm64 systems are now broken

### ISSUE THREAD

**Issue by steev** [ClementTsang/bottom#814] opened 2022-09-19 01:56 UTC
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

When running bottom on a Radxa Zero, previously I got the cpu temperature sensor, and gpu temperature sensor, now with the switch to just reading hwmon in sysfs, bottom reports No Sensors Found

### What operating system are you using?

Linux

### What architecture are you using?

arm64

### What terminal(s) are you running `bottom` on?

alacritty and windows terminal (ssh'd in to the radxa zero)

### What version of `bottom` are you running?

0.6.8 (master at 3d2c40ce2f999e )

### How did you install `bottom`?

cargo build --release

### How can we reproduce this?

run btm on a radxa zero

### Additional information

Perhaps it might be better to look in /sys/devices/virtual/thermal for sensors, or elsewhere.  Here's a quick `find` in sysfs to find all files with `temp` in the name:

```
steev@rzero:/sys$ sudo find . -iname *temp*
./kernel/tracing/events/thermal/thermal_temperature
./kernel/debug/kvm/halt_attempted_poll
./kernel/debug/tracing/events/thermal/thermal_temperature
./kernel/debug/regmap/ff634c00.temperature-sensor
./kernel/debug/regmap/ff634800.temperature-sensor
./devices/platform/soc/ff600000.bus/ff634800.temperature-sensor
./devices/platform/soc/ff600000.bus/ff634c00.temperature-sensor
./devices/virtual/thermal/thermal_zone0/trip_point_2_temp
./devices/virtual/thermal/thermal_zone0/emul_temp
./devices/virtual/thermal/thermal_zone0/trip_point_1_temp
./devices/virtual/thermal/thermal_zone0/temp
./devices/virtual/thermal/thermal_zone0/trip_point_0_temp
./devices/virtual/thermal/thermal_zone1/emul_temp
./devices/virtual/thermal/thermal_zone1/trip_point_1_temp
./devices/virtual/thermal/thermal_zone1/temp
./devices/virtual/thermal/thermal_zone1/trip_point_0_temp
./bus/platform/devices/ff634800.temperature-sensor
./bus/platform/devices/ff634c00.temperature-sensor
./bus/platform/drivers/amlogic_thermal/ff634800.temperature-sensor
./bus/platform/drivers/amlogic_thermal/ff634c00.temperature-sensor
./firmware/devicetree/base/soc/thermal-zones/cpu-thermal/trips/cpu-passive/temperature
./firmware/devicetree/base/soc/thermal-zones/cpu-thermal/trips/cpu-hot/temperature
./firmware/devicetree/base/soc/thermal-zones/cpu-thermal/trips/cpu-critical/temperature
./firmware/devicetree/base/soc/thermal-zones/ddr-thermal/trips/ddr-passive/temperature
./firmware/devicetree/base/soc/thermal-zones/ddr-thermal/trips/ddr-critical/temperature
./firmware/devicetree/base/soc/bus@ff600000/temperature-sensor@34c00
./firmware/devicetree/base/soc/bus@ff600000/temperature-sensor@34800
./firmware/devicetree/base/__symbols__/cpu_temp
./firmware/devicetree/base/__symbols__/ddr_temp
```

**Comment by ClementTsang** [comment] 2022-09-19 02:41
Interesting, will look. I don't own a radxa zero though, and I can't reproduce on my Pi, so I might need your help regarding debugging this.

Out of curiosity, does this happen on 0.6.8 stable?

**Comment by steev** [comment] 2022-09-19 02:48
That's likely because the RPi's sensors are registered with hwmon, but the ones for amlogic are not; unfortunately, arm64 sensors aren't all registered with it, and amlogic is one of the holdouts still; at least, with the 5.10 kernel, I'm building a 5.19 kernel to see if maybe they've done so, but the vendor kernel is still 5.10 if you want the "best" experience with the hardware working.

I am building 0.6.8 right now to test for you, and I don't mind bisecting at all, though it may take me a while to do so.

**Comment by ClementTsang** [comment] 2022-09-19 03:01
Thanks a ton, and yeah, I'll take a look at the suggested approach to fix this issue.

**Comment by steev** [comment] 2022-09-19 03:49
I built it anyway...  and 0.6.8 works fine:

![btm-0 6 8](https://user-images.githubusercontent.com/7370/190946848-f0510894-988c-4393-b174-2345ef08b50b.jpg)

**Comment by ClementTsang** [comment] 2022-09-19 04:23
Yep, that sounds likely. Thanks a lot for doing this btw!

**Comment by DianaNites** [comment] 2022-09-21 08:13
based on a quick check, this should be a relatively easy fix.

We just also need to check every `/sys/class/thermal/thermal_zone*` directory for a few things

- a directory starting with `hwmon`, in which case we just skip past this thermal_zone, it will be handled by the hwmon interface
- a file called `temp`, the temperature we need, with the same units as hwmon
- a file called `type`, for the sensor name

This interface is documented [here](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-thermal)

I dont have the time to implement this right this moment, but I will in a few days or so if nobody else has already done it

**Comment by ClementTsang** [comment] 2022-09-21 14:33
Should hopefully have some time today to take a crack at it.

**Comment by ClementTsang** [comment] 2022-09-23 02:40
@steev could you see if #816 fixes it on your end? Thanks!

**Comment by steev** [comment] 2022-09-23 04:05
Will do!

**Comment by steev** [comment] 2022-09-23 04:30
So, it does give a number, but it doesn't do any conversion...  i'm pretty sure my little Radxa Zero isn't actually running at 36400C... ;)

**Comment by ClementTsang** [comment] 2022-09-23 04:32
Oops, forgot to divide by 1000. :man_facepalming: Will fix in a sec.

**Comment by ClementTsang** [comment] 2022-09-23 04:34
Pushed a fix.

**Comment by steev** [comment] 2022-09-23 04:46
That looks much more realistic 👍

**Comment by ClementTsang** [comment] 2022-09-23 04:49
Merged fix, hopefully I didn't miss any other edge cases. Thanks for reporting the issue!

**Closed** 2022-09-23 04:48 UTC
Labels: bug
