### ISSUE TITLE
Runaway memory usage after running for several weeks

### ISSUE THREAD

**Issue by assarbad** [ClementTsang/bottom#359] opened 2020-12-17 08:47 UTC
### Describe the bug

After running for a few weeks (I'd reckon 4-6 weeks) in a Tmux session `btm` hogged system resources to the extent that it ground to a near-halt.

It ate about 16 GiB of the 32 GiB RAM available on the system (which also runs numerous VMs) and so the system ended up swapping like crazy and became sluggish.

From experience I'd say that the runaway memory usage was the underlying issue, leading to swapping which in turn slowed down the system. Since `btm` used only a single core it's hard to imagine how it would otherwise cause the observed slowdown.

### To reproduce

_Steps on how to reproduce the behaviour:_

Due to the long-running nature of this observed issue I have not yet been able to reproduce it. All that was done was to start `btm` (a statically linked version of it, built against musl-libc) inside one pane of a Tmux window as `root`, where it was left running as a sort of dashboard.

### bottom version (use `btm -V`)

0.5.0

### bottom config file (if one is used)

not used

### Installation method

A few weeks back I built a version 0.5.0 of `btm` using [this](https://github.com/assarbad/scripts/blob/master/build-scripts/build-rust-cli-tools).

### Platform

**Operating system and OS version:**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
$ uname -a
Linux po-s-devel 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Terminal (i.e. urxvt, kitty, etc.):**

Tmux (`2.6-3ubuntu0.2`, the version that comes packaged)

**Shell (i.e. zsh, bash, etc.):**

Bash (version that comes packaged)

_If relevant, please provide information on:_

**System info (RAM, SWAP, etc.):**

```
$ inxi -m
Memory:    Used/Total: 13564.3/32072.3MB
           Array-1 capacity: 64 GB devices: 4 EC: Single-bit ECC
           Device-1: DIMM 1 size: 8 GB speed: 2400 MT/s type: DDR4
           Device-2: DIMM 2 size: 8 GB speed: 2400 MT/s type: DDR4
           Device-3: DIMM 3 size: 8 GB speed: 2400 MT/s type: DDR4
           Device-4: DIMM 4 size: 8 GB speed: 2400 MT/s type: DDR4
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          32072       12700       10859          30        8512       19072
Swap:         32722        3632       29090
```

**Rust version (if building yourself):**

Don't recall, whatever was current at 2020-11-22.

## Additional context

_If anything hasn't been covered by the above categories, state it down here:_

```
$ inxi -C
CPU:       Quad core Intel Xeon E3-1240 v6 (-MT-MCP-) cache: 8192 KB
           clock speeds: max: 4100 MHz 1: 1408 MHz 2: 2734 MHz 3: 3069 MHz 4: 3366 MHz 5: 2969 MHz 6: 3365 MHz
           7: 3212 MHz 8: 3421 MHz
```

**Comment by ClementTsang** [comment] 2020-12-17 19:22
@assarbad Please try using 0.5.5.  0.5.4 and onwards have a fix for uncleaned memory usage.

**Comment by ClementTsang** [comment] 2020-12-17 19:28
Marking as dupe of https://github.com/ClementTsang/bottom/issues/343 for now.

**Comment by ClementTsang** [comment] 2020-12-22 00:09
Closing for now as this issue should already have been resolved, feel free to reopen.

**Closed by ClementTsang** 2020-12-22 00:09 UTC
Labels: bug, duplicate

**Comment by assarbad** [comment] 2020-12-22 17:36
> @assarbad Please try using 0.5.6, this issue should be fixed.
> 
> 0.5.4 and onwards have a fix for a broken cleaning call for a bug introduced in 0.5.0, leading to used memory never being cleared.

I will, apologies for not responding earlier. And also apologies for not being able to offer a greater level of detail.
