### ISSUE TITLE
index out of bounds crash - v0.4.7

### ISSUE THREAD

**Issue by rpwjanzen** [ClementTsang/bottom#237] opened 2020-09-17 20:36 UTC
## Describe the bug
index out of bounds while running the application long-term in a console.
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 3600 but the index is 3600', /home/ryanj/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.5/src/buffer.rs:213:14
   0: bottom::panic_hook
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/lib.rs:395
   1: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   2: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437
   3: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85
   4: core::panicking::panic_bounds_check
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:62
   5: <tui::widgets::block::Block as tui::widgets::Widget>::render
   6: <tui::widgets::chart::Chart<LX,LY> as tui::widgets::Widget>::render
             at .cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.5/src/widgets/chart.rs:410
      tui::terminal::Frame<B>::render_widget
             at .cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.5/src/terminal.rs:65
      <bottom::canvas::Painter as bottom::canvas::widgets::network_graph::NetworkGraphWidget>::draw_network_graph
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/canvas/widgets/network_graph.rs:322
   7: <bottom::canvas::Painter as bottom::canvas::widgets::network_graph::NetworkGraphWidget>::draw_network
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/canvas/widgets/network_graph.rs:63
      bottom::canvas::Painter::draw_widgets_with_constraints
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/canvas.rs:604
   8: bottom::canvas::Painter::draw_data::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/canvas.rs:573
      core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/traits/iterator.rs:655
      core::iter::traits::iterator::Iterator::fold
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/traits/iterator.rs:2022
      core::iter::traits::iterator::Iterator::for_each
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/traits/iterator.rs:658
      bottom::canvas::Painter::draw_data::{{closure}}::{{closure}}::{{closure}}
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/canvas.rs:571
      core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/traits/iterator.rs:655
      core::iter::traits::iterator::Iterator::fold
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/traits/iterator.rs:2022
      core::iter::traits::iterator::Iterator::for_each
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/traits/iterator.rs:658
      bottom::canvas::Painter::draw_data::{{closure}}::{{closure}}
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/canvas.rs:569
      core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/traits/iterator.rs:655
      core::iter::traits::iterator::Iterator::fold
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/traits/iterator.rs:2022
      core::iter::traits::iterator::Iterator::for_each
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/iter/traits/iterator.rs:658
      bottom::canvas::Painter::draw_data::{{closure}}
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/canvas.rs:564
   9: tui::terminal::Terminal<B>::draw
             at .cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.5/src/terminal.rs:187
      bottom::canvas::Painter::draw_data
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/canvas.rs:222
      bottom::try_drawing
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/lib.rs:227
      btm::main
             at .cargo/git/checkouts/bottom-38834a6a3dc1805c/54a35d6/src/bin/main.rs:199
  10: std::rt::lang_start::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
      std::rt::lang_start_internal::{{closure}}::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:52
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/sys_common/backtrace.rs:130
  11: main
  12: __libc_start_main
  13: _start
```

## To reproduce

Unknown. Issue has only occurred once.

## Platform

**bottom version (use `btm -V`):**
0.4.7

**Rust version (if building yourself):**
rustc 1.46.0 (04488afe3 2020-08-24)

## Additional context
This may be an issue in the TUI library.

**Comment by ClementTsang** [comment] 2020-09-18 03:49
Yeah, that's a TUI bug... I'll see what I can do about it, not sure exactly why it's happening there (the one line I need to see in Block's render method doesn't have a line number... the heck?).

**Comment by ClementTsang** [comment] 2020-09-18 04:57
@rpwjanzen do you know if you might have resized the terminal right before this occurred?

**Comment by ClementTsang** [comment] 2020-09-18 05:22
Note to self:

So, looking at tui-rs's code at v0.9.5, it's crashing from a `get_mut` call in [here](https://github.com/fdehau/tui-rs/blob/18714caa6079ee6e25907e1a29643f9b84fdabd4/src/widgets/block.rs#L128).

The problem?  We have no line number for *which* one it's crashing on.  It's just... crashing on one of the calls!  I don't know if my potential fix will, well, "fix" it for now... as it fixes an underlying issue which might be connected to it?  I'll try reproducing it, but if I can't, I might have to put this off or close it.

**Comment by ClementTsang** [comment] 2020-09-18 05:33
Ah.  The asset is unfortunately debug only.  That's a bit annoying.

@rpwjanzen still want to know if you had resized it when it crashed, but when I tried it in release mode on master and put a huge sleep to make resizing in time easier... I think I can reproduce it!

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 196 but the index is 196', /home/clement/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.5/src/buffer.rs:213:14
   0: bottom::panic_hook
             at src/lib.rs:402
   1: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   2: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437
   3: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85
   4: core::panicking::panic_bounds_check
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:62
   5: <tui::widgets::block::Block as tui::widgets::Widget>::render
   6: <tui::widgets::chart::Chart<LX,LY> as tui::widgets::Widget>::render
             at /home/clement/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.5/src/widgets/chart.rs:410
      tui::terminal::Frame<B>::render_widget
             at /home/clement/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.5/src/terminal.rs:65
   7: <bottom::canvas::Painter as bottom::canvas::widgets::mem_graph::MemGraphWidget>::draw_memory_graph
             at src/canvas/widgets/mem_graph.rs:115
   8: bottom::canvas::Painter::draw_widgets_with_constraints
             at src/canvas.rs:609
   9: bottom::canvas::Painter::draw_data::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at src/canvas.rs:579
      core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /home/clement/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:655
      core::iter::traits::iterator::Iterator::fold
             at /home/clement/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:2022
      core::iter::traits::iterator::Iterator::for_each
             at /home/clement/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:658
      bottom::canvas::Painter::draw_data::{{closure}}::{{closure}}::{{closure}}
             at src/canvas.rs:577
      core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /home/clement/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:655
      core::iter::traits::iterator::Iterator::fold
             at /home/clement/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:2022
      core::iter::traits::iterator::Iterator::for_each
             at /home/clement/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:658
      bottom::canvas::Painter::draw_data::{{closure}}::{{closure}}
             at src/canvas.rs:575
      core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /home/clement/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:655
      core::iter::traits::iterator::Iterator::fold
             at /home/clement/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:2022
      core::iter::traits::iterator::Iterator::for_each
             at /home/clement/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/traits/iterator.rs:658
      bottom::canvas::Painter::draw_data::{{closure}}
             at src/canvas.rs:570
  10: tui::terminal::Terminal<B>::draw
             at /home/clement/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.5/src/terminal.rs:187
      bottom::canvas::Painter::draw_data
             at src/canvas.rs:235
      bottom::try_drawing
             at src/lib.rs:234
      btm::main
             at src/bin/main.rs:207
  11: std::rt::lang_start::{{closure}}
             at /home/clement/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
      std::rt::lang_start_internal::{{closure}}::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:52
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/sys_common/backtrace.rs:130
  12: main
```

Now time to test my fix.

**Comment by ClementTsang** [comment] 2020-09-18 05:46
Change seems to work.  I can reliably crash it on master, but not on the branch.

**Comment by rpwjanzen** [comment] 2020-09-18 15:29
There is a good chance that I did resize the window. I believe I'd unplugged and external monitor at the time and the window moved between monitors. This would probably cause a resize.

**Comment by ClementTsang** [comment] 2020-09-18 16:35
Hmm, that could have done it I guess.  Going to merge the (supposed) fix then, I can't reproduce it anymore with it.

Also thanks for catching this - I don't think I would have ever noticed that this could have occurred since it's really hard to trigger normally.

**Closed** 2020-09-18 16:35 UTC
Labels: bug
