### ISSUE TITLE
RAM summary box hiding behavior

### ISSUE THREAD

**Issue by deathtrip** [ClementTsang/bottom#124] opened 2020-04-19 20:48 UTC
## Describe the bug
When launching bottom in a split terminal window (for example), the memory summary box is not visible, only the graph. Even though it would easily fit, as it has half of the screen. Resizing the window brings it back up. However the tolerance should be higher, and the box should only be hidden when the window is really too narrow to fit it.

## Platform
Arch Linux, zsh, bottom 0.3

**Comment by ClementTsang** [comment] 2020-04-19 21:20
This is caused by using a previous version of tui-rs.  This will be resolved by https://github.com/ClementTsang/bottom/issues/117.

**Closed** 2020-04-20 04:38 UTC
Labels: bug
