### ISSUE TITLE
[Bug]: Number navigations do not work

### ISSUE THREAD

**Issue by OlaoluwaM** [ClementTsang/bottom#799] opened 2022-09-03 07:42 UTC
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

Cannot use the number 1 - 7 to navigate between widgets

### What operating system are you using?

Linux

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running `bottom` on?

Tilix v1.9.5, running on Fedora 36, Gnome 42

### What version of `bottom` are you running?

0.6.8

### How did you install `bottom`?

Using cargo

### How can we reproduce this?

1. Install Bottom using the cargo installer
2. Run it and try navigating with the numbers 1 - 7
3. They do not work

### Additional information

Navigation works fine if you hold the "Shift" key and use the arrow keys

**Comment by ClementTsang** [comment] 2022-09-03 07:43
I'm confused, I don't believe this is a feature of bottom.

**Comment by ClementTsang** [comment] 2022-09-03 08:05
Clarified that the number keys in the help menu are just for the menu itself, not for the rest of the app: #800 

Closing this as it's not a bug as far as I can tell, this isn't a feature of bottom (though it might be interesting as a feature, idk).

**Closed by ClementTsang** 2022-09-03 08:05 UTC
Labels: bug, needs_more_info

**Comment by OlaoluwaM** [comment] 2022-09-03 08:12
Ah, so sorry for the mix-up. Yes, you are right. The number nav was for the help menu, not the widgets
