### ISSUE TITLE
[Bug]: CPU Utilization Shows Over 100 percent

### ISSUE THREAD

**Issue by W4JEW** [ClementTsang/bottom#776] opened 2022-08-08 19:01 UTC
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing issues](https://github.com/ClementTsang/bottom/issues) for similar issues.

### Describe the issue

I am using btm on a server running Amazon Linux (x86_64 CPU) but have also tried it on CentOS 7 (x86_64), CentOS 8 (x86_64), Ubuntu 20.04 LTS, and Raspberry Pi OS. I see the same issue across all Linux platforms.

When I view the CPU utilization on a system that has high utilization, processes consuming the most CPU will show well over 100%. In the case of the screenshot I've included, you can see the 'rnds' process is consuming 116.4% CPU. I have seen the percentage value go well beyond 500%.

Running top or htop displays the correct CPU utilization.

![btm-cpu-utilization-over-100percent](https://user-images.githubusercontent.com/63099246/183492870-e027e23f-e14a-4e0f-acd3-c9325f2f5f59.jpg)

### What operating system are you using?

Linux

### What architecture are you using?

x86_64 / AMD64, arm32

### What terminal(s) are you running `bottom` on?

macOS Terminal (2.12.7 - macOS Monterey 12.5), iTerm 3.4.16, KiTTY 0.74, PuTTY 0.76. The behavior is not related to the terminal display. The CPU utilization behavior is consistent across all terminal clients.

### What version of `bottom` are you running?

btm 0.6.8

### How did you install `bottom`?

Via binary (tar.gz) or DEB packages from GitHub.

### How can we reproduce this?

1. Run application with high CPU utilization
2. Run btm to monitor CPU utilization
3. Take note of any processes that show above 100% CPU utilization
4. Compare to utilization either via top or htop

**Comment by ClementTsang** [comment] 2022-08-09 14:11
Interesting, I'll take a look once I have some time.

**Comment by ClementTsang** [comment] 2023-01-05 02:11
Hmm, I don't seem to be able to reproduce this, even when running something that hammers the CPU like `mprime`. Could you see if 0.7.0 still has this issue? If so, are there any config files/options you're using?

**Comment by ClementTsang** [comment] 2023-02-17 07:31
Closing this for now as I can't reproduce. Anyone can feel free to reopen if they also hit this problem.

**Closed by ClementTsang** 2023-02-17 07:31 UTC
Labels: bug, needs_more_info
