### ISSUE TITLE
There is no CPU temp

### ISSUE THREAD

**Issue by markox92** [ClementTsang/bottom#1459] opened 2024-05-04 12:49 UTC
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

Windows 11

### What architecture are you using?

x86_64/AMD64

### What terminal(s) are you running bottom on that are experiencing the problem?

Windows Terminal

### What filesystem(s) are you using?

NTFS

### What version of bottom are you running?

0.9.6

### How did you install bottom?

winget install clement.bottom

### Describe the issue

No temperature sensors

### What is the expected behaviour?

CPU tempuerature, MB tempuerature etc...

### What is the actual behaviour?

Only show GPU sensors, why there is no CPU temps ?

![Screenshot 2024-05-04 144421](https://github.com/ClementTsang/bottom/assets/159203552/701fd4fe-71a2-4a5c-ab84-4f0d288c9540)

### How can we reproduce this?

run btm

**Comment by ClementTsang** [comment] 2024-05-05 08:35
Can you try running it [as admin?](https://clementtsang.github.io/bottom/nightly/support/official/#windows)

**Comment by markox92** [comment] 2024-05-05 10:54
Sure, in that case I have some strange temp which is always stay on 17C

![Screenshot 2024-05-05 125350](https://github.com/ClementTsang/bottom/assets/159203552/a4c5b1e3-82f6-4cf1-8b74-053de1dc6594)

**Comment by ClementTsang** [comment] 2024-05-05 17:38
Yeah, unfortunately I think the underlying library I use to get temperatures, sysinfo, has some issues in general for getting temperature data for certain types of hardware (https://github.com/GuillaumeGomez/sysinfo/issues/596).

I'm going to close this as it's technically not a bug with bottom, but I've opened a new ticket as a feature to investigate one of the proposed solutions to improving sensor support: #1460

**Closed by ClementTsang** 2024-05-05 17:38 UTC
Labels: bug
