### ISSUE TITLE
Customizable Keybindings

### ISSUE THREAD

**Issue by Rayqan** [ClementTsang/bottom#510] opened 2021-06-22 02:29 UTC
### Describe the feature request

Would you consider adding the ability to customize keybindings to different keys other than what they are currently set as. Thanks!

**Comment by ClementTsang** [comment] 2021-06-22 02:34
Yep, something I want to do, though I want to find some time to do in-app configuration first... along with a bevy of other things.

It does seem to be a pretty popular feature to add though (it's been suggested before in https://github.com/ClementTsang/bottom/issues/454 too) so maybe I'll bump it up in priority.

**Comment by ClementTsang** [comment] 2021-06-27 07:12
Gonna close this for organization since it's a duplicate of #454, hopefully I'll get to it in the coming weeks.

**Closed by ClementTsang** 2021-06-27 07:12 UTC
Labels: feature
