### ISSUE TITLE
Network RX and TX are swapped

### ISSUE THREAD

**Issue by DOFfactory** [ClementTsang/bottom#607] opened 2021-11-24 17:42 UTC
It appears that my linux version shows the network RX (download) and TX (upload) values inverted in bottom. Is this possible, or should this be possible to define in the app? I believe that the OS numbers are correct while bottom shows these values swapped...

**Comment by ClementTsang** [comment] 2021-11-24 18:01
Could you send more details?  The bug report form describes how to submit a bug report.

**Comment by ClementTsang** [comment] 2021-11-24 18:06
Just checked comparing to Gnome's system monitor, it seems alright on my end:

![image](https://user-images.githubusercontent.com/34804052/143291845-6e4149e3-1125-45cc-8399-00a002f02541.png)

**Comment by ClementTsang** [comment] 2021-11-25 16:38
@DOFfactory sorry for the ping, but if possible, please provide me with at least the following info:

- Your bottom version (`btm -V`)
- Your *exact* Linux distribution/version (e.x. Arch Linux, 5.15.3)
- How you installed bottom (e.x. package manager (if so, which one), cargo, manually compiled, etc.)
- Screenshots of the issue on bottom in comparison to what you're seeing on Linux

Thanks!

**Comment by ClementTsang** [comment] 2021-11-29 23:39
Since I need more info to do any further digging and can't otherwise reproduce, I'm going to close this for now. Feel free to reopen if you are still encountering this issue or have more info to help me reproduce.

**Comment by DOFfactory** [comment] 2021-11-30 00:29
Sorry, I was busy with work. I run bottom on a linux machine, Intel hardware, however the OS is proprietary: Asustor ADM 

```
> uname -a
Linux AS6604T 5.4.x #1 SMP Thu Nov 4 20:42:28 CST 2021 x86_64 GNU/Linux
```

Attaching 2 screenshots. First is a comparison of bottom with my router, and second is the comparison of bottom with ADM's traffic graph. In both cases I receive approx 2x as much data as I am sending out, however, for some reason the RX:TX ration in bottom is always 1:2. If I understand correctly Rx = receive/inbound and Tx = sending/outbound. 

![image](https://user-images.githubusercontent.com/10846169/143963290-ad1a9b04-b3b6-4a63-b94b-a8984dc51526.png)

![image](https://user-images.githubusercontent.com/10846169/143963418-d6ed765e-ffdb-4380-9947-085a99623e41.png)

**Comment by ClementTsang** [comment] 2021-11-30 00:53
Thanks for the update.  Yes, you're correct - RX is receive/inbound, TX is transmit/outbound.

Hmm, one thing that I would note is that bottom currently just simply sums *all* network interface usage - that might differ from how other tools measure it.  Maybe that could be a potential reason for it being higher?  You can explicitly filter out specific network interfaces if you want to try that (see [default config for syntax](https://github.com/ClementTsang/bottom/blob/master/sample_configs/default_config.toml)).

Also, from the screenshots, you seem to be using a version of bottom from at least before 0.6.2 - you could try updating to 0.6.4 to see if that changes anything (along with some bug fixes).

**Comment by ClementTsang** [comment] 2021-11-30 00:56
Also please include configs/command line flags you're running, if possible.

**Closed** 2022-07-02 12:58 UTC
Labels: bug, needs_more_info
