### ISSUE TITLE
Arrow keys dont work instantly when --default_widget_type is set to CPU

### ISSUE THREAD

**Issue by ShalokShalom** [ClementTsang/bottom#1341] opened 2023-11-30 02:39 UTC
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

NixOS

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running bottom on?

Konsole

### Are you using ZFS?

No

### What version of bottom are you running?

0.9.1

### How did you install bottom?

NixOS 

### Describe the issue

Setting the default widget style to CPU lets me not use the arrow keys on start
Clicking on the widget does allow me to use the arrow keys 

### What is the expected behaviour?

I start the app with --default_widget_type cpu and can immediately move with the arrow keys between the selections 

### What is the actual behaviour?

Arrow keys show no effect

### How can we reproduce this?

1. btm --dot_marker --group --rate 500 --default_widget_type cpu --color nord
2. Press arrow key down to select "AVG"
3. Not working
4. Click on the widget
5. Press the arrow key
6. See its working

### Additional information

Thanks a lot 🥳

**Comment by ClementTsang** [comment] 2023-11-30 03:13
Does this occur with the newest stable release (0.9.6)?

**Comment by ClementTsang** [comment] 2023-11-30 03:53
Just tested it - this is technically correct behaviour, you would have the same behaviour if you started on the process widget and selected the _graph_ part of the CPU widget, which is what is selected by default if you do `--default_widget_type cpu`.

**Comment by ShalokShalom** [comment] 2023-11-30 10:10
I suggest a simple line, that transitions one into the other, after the startup
Ideally, it would also save the position past closing the app, while I guess thats a separate issue.

Thanks

**Comment by ClementTsang** [comment] 2023-11-30 16:16
> I suggest a simple line, that transitions one into the other, after the startup

Sorry, not exactly sure what you mean by this - do you mean like combining the two with a connector? I guess that's doable, though I don't know if I want to do that.

As for saving the position, yeah that seems reasonable to add at some point.

**Comment by ShalokShalom** [comment] 2023-12-02 18:51
As far as I understand, starts the app now in a state, in which it is impossible to move the cursor by arrow keys 

And I understand, that there is another state, which allows that

Why not simply transition from one state into the other automatically?
At startup?

**Comment by ClementTsang** [comment] 2023-12-03 02:30
:shrug: I don't really feel like that's a necessity, and I would rather address the crux of your issue (that you wanted to select the average CPU by default).

**Comment by ClementTsang** [comment] 2023-12-06 03:59
Closing as this is not a bug, and in favour of https://github.com/ClementTsang/bottom/issues/1350.

**Closed by ClementTsang** 2023-12-06 03:59 UTC
