### ISSUE TITLE
on the top or bottom there should be some basic stats like uptime,users, as the 'top' has

### ISSUE THREAD

**Issue by mrlee14** [ClementTsang/bottom#1435] opened 2024-03-27 20:26 UTC
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for similar feature requests.

### Describe the feature request

Status bars bottom and top perhaps to show some more sys data...

**Comment by ClementTsang** [comment] 2024-03-27 21:57
Kinda a dupe of https://github.com/ClementTsang/bottom/issues/235, gonna close this for now.

**Closed by ClementTsang** 2024-03-27 21:57 UTC
Labels: duplicate, feature
