### ISSUE TITLE
Show processes not owned by current user

### ISSUE THREAD

**Issue by ReagentX** [ClementTsang/bottom#287] opened 2020-11-02 23:31 UTC
### Describe the feature request

Running `htop` with `sudo` exposes more processes that often are using resources. `btm` does not show root processes so it can report high CPU usage without showing the processes actually doing the work.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1920666/97930519-911efa80-1d39-11eb-828d-7378e3652430.png">

**Comment by ClementTsang** [comment] 2020-11-03 00:46
Seems like a dupe of #236?  I plan on getting to it after 0.5.0.

**Comment by ClementTsang** [comment] 2021-05-20 22:44
I think(?) this is covered by now.

![image](https://user-images.githubusercontent.com/34804052/119057914-5c078c00-b99b-11eb-86c4-b6a15e1fd56d.png)

Closing this, feel free to reopen.

**Closed by ClementTsang** 2021-05-20 22:44 UTC
Labels: feature
